### ISSUE TITLE
Qustions about the BreastPathQ dataset.

### ISSUE THREAD

**Issue by JohnleeHIT** [srinidhiPY/SSL_CR_Histo#2]
![图片](https://user-images.githubusercontent.com/28437074/147712795-4423386b-5267-4b80-9330-5901fe0a3fc4.png)
Thanks for your effort for releasing this great code, I have some issues towards the BreastPathQ dataset. I wander where can i get the target of the testing set of BreastPathQ dataset, since the official site on grand challenge only have labels of training and validation set.

**Comment by srinidhiPY** [comment]
The BreastPathQ challenge dataset is publicly available here: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=52758117

Corresponding details regarding the dataset can be found in this paper: https://www.spiedigitallibrary.org/journals/journal-of-medical-imaging/volume-8/issue-3/034501/SPIE-AAPM-NCI-BreastPathQ-Challenge--an-image-analysis-challenge/10.1117/1.JMI.8.3.034501.full
