### ISSUE TITLE
Pretrained weight

### ISSUE THREAD

**Issue by szc19990412** [srinidhiPY/SSL_CR_Histo#3]
Hi, thanks for your amazing work! I have a question that when I try to load the ptetrained weight `Pretrained_models/Camelyon16_pretrained_model.pt`, it has some problem. 
![image](https://user-images.githubusercontent.com/58326452/156770491-9c406a07-f8a1-451e-97b3-11af9c61a353.png)
I think this weight is damaged, can you please check the validity of the weight. Looking forward to your reply！

**Comment by szc19990412** [comment]
I try the `git-lfs clone https://github.com/srinidhiPY/SSL_CR_Histo.git`
![image](https://user-images.githubusercontent.com/58326452/156777502-8cababd1-b164-4ddf-8774-bc45589d8584.png)
but only get `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`
Maybe Google Cloud Disk can solve this problem very well.

**Comment by srinidhiPY** [comment]
Hi, I am sorry for that. I have attached the google drive link to download the pre-trained weights here: https://drive.google.com/drive/folders/19VNVc7LfE5_-smHJWWIQSG0atFNXKAxV?usp=sharing

Thanks for your interest in our work.
